name: ARM64 Cross Build Task
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NDK r27d manually（避开第三方Action兼容问题）
        run: |
          sudo apt update
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip -q android-ndk-r27d-linux.zip
          echo "NDK_PATH=$PWD/android-ndk-r27d" >> $GITHUB_ENV

      - name: Test ARM64 compile env
        run: |
          mkdir -p build
          cd build
          echo "Environment ready, path: ${{ env.NDK_PATH }}"
